# Nombre del archivo principal sin la extensión .tex
MAIN = main_plenary

# Comando para compilar
# La línea de abajo (pdflatex) DEBE empezar con un TAB
all:
	pdflatex $(MAIN).tex
	pdflatex $(MAIN).tex

# Comando para limpiar
# La línea de abajo (rm) DEBE empezar con un TAB
clean:
	rm -f *.aux *.log *.nav *.out *.snm *.toc *.synctex.gz